project:
  type: website

execute:
  freeze: auto

website:
  title: "IA para desarrolladores"
  navbar:
    left:
      - text: Inicio
        file: qmd/index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Fundamentos"
        contents:
          - qmd/10_fundamentos/10_intro.qmd
          - qmd/10_fundamentos/20_linear_regression.qmd
          - qmd/10_fundamentos/30_linear_regression2.qmd
          - qmd/10_fundamentos/40_logistic_regression.qmd
          - qmd/10_fundamentos/50_neural_networks.qmd
      - section: "LLM"
        contents:
          - qmd/20_LLM/00_introduction.qmd
          - qmd/20_LLM/05_tokenization.qmd
          - qmd/20_LLM/10_word_embeddings.qmd
          - qmd/20_LLM/20_word2vec.qmd
          - qmd/20_LLM/30_similarity.qmd
          - qmd/20_LLM/40_attention.qmd
          - qmd/20_LLM/50_decoder.qmd
      - section: "Hugging Face"
        contents:
          - qmd/30_hugging_face/10_intro.qmd
          - qmd/30_hugging_face/20_fine_tunning.qmd
      - section: "Guía para desarrolladores"
        contents:
          - qmd/40_guia_desarrolladores/10_ollama.qmd
          - qmd/40_guia_desarrolladores/20_api.qmd
          - qmd/40_guia_desarrolladores/30_params.qmd
          - qmd/40_guia_desarrolladores/40_templates.qmd
          - qmd/40_guia_desarrolladores/50_memory.qmd
          - qmd/40_guia_desarrolladores/60_ingenieria_prompts.qmd
      - section: "Apéndices"
        contents:
          - qmd/90_apendices/10_derivadas.qmd
          - qmd/90_apendices/20_matrices.qmd
          - text: "Demo: Transformaciones lineales"
            href: linear_transformations.html
            target: _blank
          - text: "Presentación 2025"
            href: presentacion_2025.html
            target: _blank
format:
  html:
    charset: "utf-8"
    lang: es
    theme:
      - cosmo
      - brand
    toc: true
    code-overflow: wrap
resources:
  - presentacion_2025.html
  - linear_transformations.html
  - README.md
