project:
  type: website

execute:
  freeze: auto
  
website:
  title: "IA para desarrolladores"
  navbar:
    left:
    - text: Inicio
      file: qmd/index.qmd
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Fundamentos"
          contents:
            - qmd/10_fundamentos/10_intro.qmd
            - qmd/10_fundamentos/20_linear_regression.qmd
            - qmd/10_fundamentos/30_linear_regression2.qmd
            - qmd/10_fundamentos/40_logistic_regression.qmd
            - qmd/10_fundamentos/50_neural_networks.qmd
        - section: "LLM"
          contents:
            - qmd/20_LLM/00_introduction.qmd
            - qmd/20_LLM/10_word_embeddings.qmd
        - section: "Apéndices"
          contents:
              - qmd/90_apendices/10_derivadas.qmd
              - text: "Presentación 2025"
                href: presentacion_2025.html
                target: _blank
format:
  html:
    charset: "utf-8"
    lang: es
    theme:
      - cosmo
      - brand
    toc: true
resources:
    - presentacion_2025.html
    - README.md


