model_list:
  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: "http://localhost:11434"

general_settings:
  master_key: "sk-zd0MSMnFPCQs1vE2_0Zfa6gUZosrVzjiIo8xqD0exCw"
